import { PixelLogo } from '../components/PixelLogo'
import { useState } from 'react'
import { ArrowRight, ArrowUpRight, Check, Copy, Github, Mail, MapPin, ArrowUp, GraduationCap } from 'lucide-react'
import { profile, projects, experience, education, skills, interests } from '../data/portfolio'
import { ExternalLink, SectionTitle } from '../components/ui'
export function Content() {
 const [filter, setFilter] = useState('All work')
 const [copyState, setCopyState] = useState('')
 async function copyEmail() {
  try { await navigator.clipboard.writeText(profile.email); setCopyState('Email copied.') }
  catch { setCopyState('Please select and copy the email address above.') }
 }
 return <>
 <section id="education" className="section"><SectionTitle number="01" label="EDUCATION" title="A foundation in computer science."/><div className="education-list">{education.map(item=><article key={item.degree}><div className="education-icon"><GraduationCap size={23}/></div><div><h3>{item.degree}</h3><p>{item.school}</p></div><div className="education-meta"><span>{item.year}</span><strong>GPA {item.gpa}</strong></div></article>)}</div></section>
 <section id="skills" className="section bordered-section"><SectionTitle number="02" label="SKILL SET" title="Languages, tools, and technologies."/><div className="skills-grid">{skills.map((group,i)=><article className="skill-group" key={group.name}><span className="skill-number">0{i+1}</span><h3>{group.name}</h3><p>{group.note}</p><div className="skill-items">{group.items.map(skill=><span key={skill}>{skill}</span>)}</div></article>)}</div><p className="skill-footnote">Strongest in Python; comfortable with SQL. Working knowledge of JavaScript and TypeScript, with prior experience in C, C++, Java, and Linux.</p></section>
 <section id="about" className="section about-section"><SectionTitle number="03" label="ABOUT" title="Curious by nature. Builder by practice."/><div className="about-grid"><div><p className="lead">{profile.about}</p><p>{profile.approach}</p></div><aside className="about-note"><span className="small-label">BEYOND THE CODE</span><h3>Better work, together.</h3><p>Founder and secretary of NMSU’s International Collaborative Coding Club, organizing activities and coordinating software projects.</p><div className="language-note">Mandarin · Native <span/> English · Fluent</div></aside></div></section>
 <section id="experience" className="section bordered-section"><SectionTitle number="04" label="EXPERIENCE" title="Research with real questions."><p>Investigating risks.<br/>Connecting knowledge.</p></SectionTitle><div className="timeline">{experience.map((item,index)=><article className="experience-row" key={item.date}><div className="experience-date"><span className="timeline-dot"/><span>{item.date}</span><small>0{index+1}</small></div><div><p className="small-label">{item.label}</p><h3>{item.role}</h3><p className="organization">{item.org}</p><ul>{item.bullets.map(bullet=><li key={bullet}>{bullet}</li>)}</ul><div className="tags">{item.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div></article>)}</div></section>
 <section id="projects" className="section projects-section"><SectionTitle number="05" label="SELECTED PROJECTS" title="Ideas, turned into working systems."><p>A few things I’ve built<br/> and problems I’ve worked through.</p></SectionTitle><div className="filters" role="group" aria-label="Filter projects">{['All work','AI & Data','Web','Systems & Games'].map(category=><button key={category} aria-pressed={filter===category} onClick={()=>setFilter(category)}>{category}</button>)}</div><p className="sr-only" aria-live="polite">{projects.filter(p=>filter==='All work'||p.category===filter).length} projects shown</p><div className="project-grid">{projects.filter(p=>filter==='All work'||p.category===filter).map(project=><article className={'project-card project-'+projects.indexOf(project)} key={project.name}><div className="project-visual"><div className="project-meta"><span>{project.category}</span><span>0{projects.indexOf(project)+1}</span></div><div className="project-word">{project.name}<span>_</span></div><div className="project-flow" aria-label="Project technical flow">{project.flow.map((step,i)=><span key={step}>{i>0&&<ArrowRight size={13} aria-hidden="true"/>}{step}</span>)}</div></div><div className="project-body"><p className="small-label">{project.subtitle}</p><h3>{project.description}</h3><p>{project.detail}</p><div className="tags">{project.tech.map(tech=><span key={tech}>{tech}</span>)}</div>{(project.github||project.demo)&&<div className="project-links"><ExternalLink href={project.github}><Github size={16}/> Source code</ExternalLink><ExternalLink href={project.demo}>Live demo</ExternalLink></div>}</div></article>)}</div></section>
 <section id="interests" className="section interests-section"><SectionTitle number="06" label="OFF THE CLOCK" title="Still curious."/><p className="interests-intro">Exploring new systems, new ideas, and places beyond the screen.</p><div className="interest-list">{interests.map((interest,index)=><span key={interest}><span className="interest-number">0{index+1}</span>{interest}</span>)}</div></section>
 <section id="contact" className="section contact-section"><p className="eyebrow"><span>07</span> / GET IN TOUCH</p><div className="contact-grid"><div><h2>Let’s build<br/><span>something useful.</span></h2><p>{profile.availability}</p><div className="contact-location"><MapPin size={16}/>{profile.location}, USA</div></div><div className="contact-details"><span className="small-label">START A CONVERSATION</span><a className="email-link" href={'mailto:'+profile.email}>{profile.email}<ArrowUpRight size={22}/></a><button className="copy-button" onClick={copyEmail}>{copyState==='Email copied.'?<Check size={15}/>:<Copy size={15}/>} {copyState==='Email copied.'?'Copied':'Copy email'}</button><p role="status" className="copy-status">{copyState}</p><div className="contact-social"><ExternalLink href={profile.github}><Github size={18}/> GitHub</ExternalLink><ExternalLink href={profile.linkedin}>LinkedIn</ExternalLink><a href={'mailto:'+profile.email}><Mail size={18}/> Email <ArrowUpRight size={16}/></a></div></div></div></section>
 <footer><div><a href="#home" className="wordmark" aria-label="Xindi Zheng home"><PixelLogo/></a><span>© 2026 Xindi Zheng</span><span>Built with React & TypeScript.</span><a href="#home" className="back-top">Back to top <ArrowUp size={15}/></a></div></footer>
 </>
}




